In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr1 = np.array([6,7,8,9,10])

In [11]:
arr1

array([ 6,  7,  8,  9, 10])

In [12]:
arr+arr1

array([ 7,  9, 11, 13, 15])

In [14]:
arr+100

array([101, 102, 103, 104, 105])

Broadcasting

In [ ]:
arr2 = np.array([1,2,3])
arr3 = np.array([[4],[5],[6]])

In [21]:
arr2+arr3

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])