In [ ]:
import numpy as np

In [2]:
num_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [3]:
num_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
reshaped = num_array.reshape(3,4)

In [5]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Flatten

In [6]:
flattened = reshaped.flatten()

In [7]:
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

ravel

In [8]:
raveled = reshaped.ravel()

In [9]:
raveled

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

flatten vs ravel

In [10]:
flattened[0] = 99

flattened

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
raveled[5] = 0

In [15]:
reshaped

array([[99,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10, 11, 12]])

So the Concept is flatten basically makes a copy and change it. On the other hand ravel change the Original array.