Slicing

In [1]:
import numpy as np

In [5]:
num_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [6]:
num_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
num_array[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
num_array[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
num_array[0:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
num_array[0:1,2:]

array([[3, 4]])

In [14]:
num_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
num_array[0:1]

array([[1, 2, 3, 4]])

In [18]:
num_array[0:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [20]:
num_array[0:3:2,0:5]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])