In [1]:
import numpy as np

In [2]:
num_array = np.array([1,2,3,4,5])

In [3]:
num_array

array([1, 2, 3, 4, 5])

In [4]:
num_array1 = np.array([[1,2,3,4,5],[10,20,30,40,50]])

In [6]:
num_array1

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

Functions

In [7]:
num_array.dtype

dtype('int64')

In [8]:
num_array1.dtype

dtype('int64')

In [11]:
num_array.shape

(5,)

In [12]:
num_array.size

5

In [13]:
num_array.ndim

1

In [17]:
zeros = np.zeros((2,3),dtype=int)

In [18]:
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
ones = np.ones((2,3),dtype=int)

In [20]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
arr_arange = np.arange(10)

In [23]:
arr_arrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr_d = np.linspace(1,5,10)

In [27]:
arr_d

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])