In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [3]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Indexing

In [7]:
array[0]

array([1, 2, 3, 4])

In [8]:
array[1][1]

np.int64(6)

In [9]:
array[2][1] 

np.int64(10)

In [10]:
array[-1]

array([ 9, 10, 11, 12])

In [13]:
array[-1][-1] =11

In [14]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 11]])

In [16]:
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 3, 3, 3]])

In [15]:
array[2]=3

Slicing

In [12]:
array[0:1]

array([[1, 2, 3, 4]])